### ISSUE TITLE
Presenza del carattere Unicode U+FEFF

### ISSUE THREAD

**Issue by aborruso** [openamat/Official-Data#1]
Nei file shapes.txt, stop_times.txt e stops.txt è presente il carattere Unicode U+FEFF.

Si tratta del BOM, in sè non è un errore, ma sono diversi da tutti gli altri file. E' bene uniformare tutto a UTF-8, anche perché l'UTF-8-BOM può essere un encoding problematico per la lettura on the fly da parte di diversi client.

**Comment by dlion** [comment]
Su linux basta dare questo comando all'interno della directory

``` sh
for i in `ls *.txt`; do ( sed 's/\xEF\xBB\xBF//' < $i > $i.new ); done
```

Compariranno nella cartella file `*.new` senza carattere unicode.

**Comment by aborruso** [comment]
@dlion grazie, la soluzione l'avevo anche io :)

Ma qui sopratutto stiamo raccogliendo elementi per chiedere ad AMAT di pubblicare nuovi dati "puliti". 

Grazie ancora

**Comment by dlion** [comment]
@aborruso  Sì certo, più che altro per avere una soluzione già pronta per chi volesse già fin da subito mettere mano ai files fornitoci.

Grazie a te!

**Comment by aborruso** [comment]
Risolto con aggiornamento dati del 22/07/2016 https://www.comune.palermo.it/opendata_dld.php?id=384

**Comment by aborruso** [comment]
come segnalato da @patperu in realtà nella release `v9` del 22-07-2016 i file sono tutti "UTF-8 Unicode (with BOM) text, with CRLF line terminators".

**Comment by aborruso** [comment]
@patperu in GTFS file [official requirements](https://developers.google.com/transit/gtfs/reference/file-requirements) you can read:

> Files should be encoded in UTF-8 to support all Unicode characters. Files that include the Unicode byte-order mark (BOM) character are acceptable. Please see the Unicode FAQ for more information on the BOM character and UTF-8.

**Comment by patperu** [comment]
Ciao @aborruso , 
the release V10 is "pure" UTF-8. No BOM :+1:
