### ISSUE TITLE
Disallineamento tra sito AMAT e GTFS pubblicato

### ISSUE THREAD

**Issue by aborruso** [openamat/Official-Data#10]
Sul sito AMAT - http://www.amat.pa.it/Le_Linee/linee_orario.php - è presente un elenco di linee. Nel file GTFS pubblicato il 15/07/2016 non sono presenti tutte.

In particolare nel GTFS mancano: 100, 106, 108, 226, 231, 307, 380, 442, 534, 606, 619, 806, 812, 86, H2, NAVETTA CIVICO, NAVETTA EXPRESS, NOTTURNO 11, NOTTURNO 12, NOTTURNO 21, NOTTURNO 22.

C'è da verificare se è più aggiornato il sito o il file GTFS

**Comment by patperu** [comment]
Ciao Andy,
ci sono anche tre linee nel file GTFS (224P, 628P, ARANC) che non sono presenti sul sito di AMAT. 
Vedi https://gist.github.com/patperu/5826510e88126d7eb1039fbc3827021f#file-matched_routes-csv
:wave:

**Comment by aborruso** [comment]
Con l'aggiornamento v9 del 22-07-2016 persiste ancora il disallineamento:
- sul sito sono presenti queste linee 106, 108, 307, 619, 812, 86, NAVETTA CIVICO, NAVETTA EXPRESS, NOTTURNO 11, NOTTURNO 12, NOTTURNO 21, NOTTURNO 22, TRAM1, TRAM2, TRAM3, TRAM4, non presenti nel GTFS;
- sul GTFS sono presenti le linee 224P, 628P e EXPR, non elencate nel sito

**Comment by aborruso** [comment]
Aggiungo la risposta dell'ing. Lumione di AMAT che chiarisce alcuni dei problemi di sopra. Bisogna aggiornare il tutto alla luce di quanto ci scrive. Sotto il testo

> Sul sito AMAT sono presenti alcune linee non presenti nel feed GTFS, in particolare le seguenti linee: 106, 108, 307, 619, 812, NAVETTA CIVICO, NOTTURNO 11, NOTTURNO 12, NOTTURNO 21, NOTTURNO 22, TRAM1, TRAM2, TRAM3, TRAM4. La linea NAVETTA CIVICO, in realtà, è una navetta interna all’Ospedale Civico, per la quale dubito possa esserci un reale interesse della collettività per quel che riguarda la pianificazione degli spostamenti cittadini. La NAVETTA EXPRESS indicata sul sito AMAT coincide con quella che nel feed viene denominata con il nome breve EXPR e che i requisiti espressi nel documento General Transit Feed Specification non ci consentono di denominare con un nome più lungo. Le linee 224P, 628P ed in generale le linee il cui nome termina con il carattere “P” designano i cosiddetti “prolungamenti” delle corrispondenti linee da cui esse stesse sono ricavate. Per essere più chiari, va detto che alcune linee, come la 224 e la 628, effettuano alcune corse in prolungamento verso un terzo terminale ma poiché il documento General Transit Feed Specification non prevede tale possibilità ed al fine di comprendere le corse di prolungamento nel feed GTFS, in modo da non escludere gli orari di tali corse nei vari ed eventuali trip planner, si è pensato di raggrupparle all’interno di nuove linee fittizie, le cui denominazioni sono ricavate dai nomi delle linee di provenienza, con l’aggiunta del carattere “P” finale. Le corse in prolungamento, sul sito AMAT, sono indicate con il carattere *. Per quanto riguarda le altre linee non presenti nel feed GTFS, Le dico che stiamo lavorando per includerle in tempi brevissimi.

**Comment by aborruso** [comment]
Alla luce di quanto indicato [qui](https://github.com/openamat/Official-Data/wiki/noteDati) la differenza tra sito e GTFS è ristretta a 86, 812, 619, 307, 108, 106, NOTTURNO 22, NOTTURNO 21, NOTTURNO 12, NOTTURNO 11, TRAM4, TRAM3, TRAM2, TRAM1, ad oggi non presenti sul GTFS.

**Comment by aborruso** [comment]
Chiudo issue e apro nuova issue rispetto a release 10 del dataset (a5c7bb4)
