### ISSUE TITLE
Ci sono numeri che mi sembrano strani. Sbaglio la logica del conteggio?

### ISSUE THREAD

**Issue by aborruso** [openamat/Official-Data#11]
Ho voluto interrogare il db dei dati AMAT per fare qualche conteggio. Ho usato il db in formato [sqlite](https://github.com/openamat/Products/blob/master/data/201607/amat201607.sqlite), che mi sembra il più comodo.

Le relazioni tra le tabelle di un GTFS sono illustrate nella meravigliosa immagine in fondo (e anche nella [documentazione ufficiale](https://developers.google.com/transit/gtfs/reference/) del GTFS).

Sfogliano le tabelle in questa direzione `stops > stop_times > trips > routes` ho eseguito una query per ottenere tutti i record che fanno riferimento a tutti i bus in partenza dal capolinea del 101 (`stop_id=1970`), per le rotte nella direzione stadio>stazione (`"direction_id"=0`), nei giorni feriali (`"service_id"="FR"`).
Ovviamente sto esaminando i dati della sola linea 101.

Il primo record è alle 5:15 e l'ultimo alle 22:40, ovvero 1045 minuti, per un totale di 431 partenze dal capolinea. Ovvero **un autobus in partenza ogni 3 minuti** (poco meno).

Mi sembra un numero grande. Non prendo i bus, ma non mi sembra un numero reale.

Devo dire che mi sembra di avere preso una cantonata, ma vorrei un riscontro.

``` SQL
SELECT 
"a"."stop_id" AS "stop_id", "a"."stop_code" AS "stop_code", "a"."stop_name" AS "stop_name", "a"."zone_id" AS "zone_id", 
"a"."parent_station" AS "parent_station", "b"."trip_id" AS "trip_id", "arrival_time","departure_time","route_short_name",
"route_long_name","direction_id","service_id", "a"."geometry" AS "geometry"
FROM "stops" AS "a"
LEFT JOIN 
(SELECT 
    "a"."trip_id" AS "trip_id", "a"."stop_id" AS "stop_id", "a"."stop_sequence" AS "stop_sequence", 
    "a"."arrival_time" AS "arrival_time","a"."departure_time" AS "departure_time",
    "a"."stop_headsign" AS "stop_headsign", "a"."pickup_type" AS "pickup_type", "a"."drop_off_type" AS "drop_off_type", 
    "a"."shape_dist_traveled" AS "shape_dist_traveled", "a"."timepoint" AS "timepoint", "d"."trip_id" AS "trip_id_1",
    "d"."route_id","route_short_name","route_long_name","direction_id","service_id"
    FROM "stop_times" AS "a"
    LEFT JOIN 
    (SELECT "a"."trip_id" AS "trip_id", "a"."route_id" AS "route_id","a"."direction_id" AS "direction_id",
        "a"."service_id" AS "service_id", "c"."route_short_name" AS "route_short_name", 
        "c"."route_long_name" AS "route_long_name"
        FROM "trips" AS "a"
        LEFT JOIN "routes" AS "c" USING ("route_id"))AS "d" USING ("trip_id")
    where arrival_time like "%:%" AND "route_id"=101) AS "b" USING ("stop_id")
where "direction_id"=0 AND "service_id"="FR" AND stop_id=1970
order by departure_time,CAST("trip_id" AS INTEGER),stop_name
```

![image](https://cloud.githubusercontent.com/assets/30607/16901996/b67b1fa0-4c52-11e6-863b-9fd773790072.png)

**Comment by patperu** [comment]
Ciao Andy,
well, I am getting the same numbers....

``` R
> # https://github.com/openamat/Official-Data/issues/11
> t1 <- filter(amat$trips_df, route_id == "101", direction_id == 0 & service_id == "FR")
> stop_t <- filter(amat$stop_times_df, trip_id %in% t1$trip_id) %>%
+               filter(stop_id == "1970") %>%
+               arrange(arrival_time) %>%
+               filter(stop_sequence == 1)
> head(stop_t)
# A tibble: 6 x 10
  trip_id arrival_time departure_time stop_id stop_sequence stop_headsign pickup_type drop_off_type shape_dist_traveled timepoint
    <chr>        <chr>          <chr>   <chr>         <int>         <chr>       <int>         <int>               <dbl>     <int>
1     309     05:15:00       05:15:00    1970             1          <NA>           0             0                   0         1
2     358     05:20:00       05:20:00    1970             1          <NA>           0             0                   0         1
3    1070     05:24:00       05:24:00    1970             1          <NA>           0             0                   0         1
4    1141     05:30:00       05:30:00    1970             1          <NA>           0             0                   0         1
5     456     05:30:00       05:30:00    1970             1          <NA>           0             0                   0         1
6     530     05:35:00       05:35:00    1970             1          <NA>           0             0                   0         1
> tail(stop_t)
# A tibble: 6 x 10
  trip_id arrival_time departure_time stop_id stop_sequence stop_headsign pickup_type drop_off_type shape_dist_traveled timepoint
    <chr>        <chr>          <chr>   <chr>         <int>         <chr>       <int>         <int>               <dbl>     <int>
1    1187     22:00:00       22:00:00    1970             1          <NA>           0             0                   0         1
2     454     22:00:00       22:00:00    1970             1          <NA>           0             0                   0         1
3    1284     22:06:00       22:06:00    1970             1          <NA>           0             0                   0         1
4     528     22:10:00       22:10:00    1970             1          <NA>           0             0                   0         1
5    1334     22:12:00       22:12:00    1970             1          <NA>           0             0                   0         1
6     406     22:40:00       22:40:00    1970             1          <NA>           0             0                   0         1
> length((stop_t$trip_id))
[1] 431
```

**Comment by gbvitrano** [comment]
Applicando il semplice filtro di excel ottengo sempre 431 partenze (direction_id=0), ma la cosa strana è che se filtro per direction_id=1 gli arrivi sono 425. 
Sbaglio qualccosa? Il numero delle partenze non dovrebbe essere uguale agli numero di arrivi?
![101_partenze](https://cloud.githubusercontent.com/assets/20488693/16910530/6fbf0ff4-4cd9-11e6-87e7-b31e16c1cbef.jpg)
![101_arrivi](https://cloud.githubusercontent.com/assets/20488693/16910532/773bffd0-4cd9-11e6-99a0-a17ece07b12f.jpg)

**Comment by aborruso** [comment]
@gbvitrano mi fa piacere vederti anche qui :)

La direction è relativa al verso, quindi in un caso stadio verso stazione e nell'altro stazione verso stadio. Per risponderti dovrei capirne di più rispetto a queste reti e ne so poco.
Se tutte le rotte di una tratta, sono quelle di ritorno di quella nell'altro verso, hai ragione e dovrebbe essere un errore.
Ma è possibile che ci siano tratte che non siano di ritorno, ma solo dedicate a una tratta in un certo verso, o che tutti i mezzi non tornino indietro?

In ogni caso mi sembra un'ottima osservazione.

Ti consiglio di aprire una nuova issue in casi come questi, in modo che ogni tipo di possibile errore/problema possa essere discusso in un contenitore distinto.

**Comment by aborruso** [comment]
Chiudo la issue, con la release v9 del dataset siamo passati da 431 a 192.
