### ISSUE TITLE
Linee con quantità di corse diverse nelle due direzioni

### ISSUE THREAD

**Issue by aborruso** [openamat/Official-Data#13]
La tabella `trips` contiene la colonna `direction_id`, che può essere o `0` o `1`.

E' corretto che per alcune linee il numero totale (in un giorno feriale) nelle due direzioni non sia coincidente?
E' un'annotazione che si deve a @gbvitrano

Sotto la tabella di sintesi

| Linea | Quantità in direzione "0" | Quantità in direzione "1" | Differenza |
| --- | --- | --- | --- |
| 101 | 431 | 425 | 6 |
| 704 | 121 | 124 | -3 |
| 243 | 113 | 115 | -2 |
| 731 | 108 | 115 | -7 |
| 628 | 107 | 93 | 14 |
| 625 | 105 | 106 | -1 |
| 529 | 103 | 107 | -4 |
| 118 | 102 | 103 | -1 |
| 616 | 92 | 96 | -4 |
| 110 | 89 | 90 | -1 |
| 210 | 86 | 87 | -1 |
| 462 | 68 | 64 | 4 |
| 603 | 65 | 64 | 1 |
| 628P | 27 | 25 | 2 |
| 389 | 4 | 2 | 2 |

**Comment by gbvitrano** [comment]
analizando il nuovo file trips del file amat_feed_gtfs_v9 ho visto che le linee 243, 625, 529, 188, 110, 603 sono state corrette.
Ma ci sono ancora problemi 
![linee_0_1](https://cloud.githubusercontent.com/assets/20488693/17051793/b938f4b4-4ffa-11e6-813f-a3fb6bd5f98a.jpg)

Ps...perdonate la mia ignoranza...ma come posso postare direttamente la tabella qui?

**Comment by aborruso** [comment]
@gbvitrano nelle issue di github puoi scrivere testo "ricco" nel fantastico markdown. 

Riferimenti utili:
- come scrivere in github [https://help.github.com/articles/about-writing-and-formatting-on-github/](https://help.github.com/articles/about-writing-and-formatting-on-github/);
- la pagina "storica" del md [https://help.github.com/articles/about-writing-and-formatting-on-github/](https://help.github.com/articles/about-writing-and-formatting-on-github/);
- qui un riferimento alle tabelle [https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables)

**Comment by aborruso** [comment]
L'ing Lumione di AMAT ci ha scritto quanto riportato sotto:

> Le segnalo che il numero di corse previste in una linea nelle due direzioni può differire anche di parecchie unità, in relazione al numero di vetture impiegate nella linea ed ai terminali (capolinea) da cui tali vetture eseguono rispettivamente la prima ed ultima corsa utile.

**Comment by gbvitrano** [comment]
Vediamo se ho capito... Esempio il nostro bel **101** parte dal capolinea dello Stadio, dopo aver fatto il suo giro, arriva alla Stazione e li finisce la corsa! Per rientrare al capolinea/deposito se ne va in giro cosi... quindi direction_id 0 = **1 corsa** e direction_id =1 **0 corse**  ---   Funziona così...?
![pulman-1](https://cloud.githubusercontent.com/assets/20488693/17075997/b9420926-50a6-11e6-8543-e3b20c14eb5e.png)

**Comment by aborruso** [comment]
>  la differenza di rotte nelle due direzioni è corretta poiché, come ho già avuto modo di spiegare, dipende dal numero di bus impiegati in ciascuna linea e dai terminali (capolinea) da cui i bus eseguono rispettivamente la prima corsa utile e l'ultima corsa utile.
