### ISSUE TITLE
Geometrie che sembrano errate

### ISSUE THREAD

**Issue by gbvitrano** [openamat/Official-Data#20]
shapes_id 1080 vicino il parcheggio basile, taglia gli edifici.

![errore_shape_id_1080](https://cloud.githubusercontent.com/assets/20488693/18433094/08ecb3d8-78e6-11e6-9434-c45bb2f2d233.jpg)

**Comment by aborruso** [comment]
errore confermato anche nell'update del 20/09/2016 https://www.comune.palermo.it/opendata_dld.php?id=389

**Comment by gbvitrano** [comment]
errore corretto nell'update del 28/09/2016 https://www.comune.palermo.it/opendata_dld.php?id=389

**Comment by patperu** [comment]
Thank you for the info!
