### ISSUE TITLE
GTFS data at Transitfeeds is outdated

### ISSUE THREAD

**Issue by patperu** [openamat/Official-Data#6]
Hello,
the GTFS data at [Transitfeeds](http://transitfeeds.com/p/amat-palermo-spa/540) is outdated. It seems to be useful to have one static link to the GTFS file (see this issue https://github.com/TransitFeeds/TransitFeeds-Public/issues/162).
Maybe it's possible the use a file name without a version number (like "_v7", "_v8")?

Ciao
Patrick

**Comment by aborruso** [comment]
hi @patperu I have asked yesterday to transitland to update theri data.

In the past month I have asked also to comune di Palermo and AMAT to have a fixed URL for the latest update data.

I will write them again

**Comment by patperu** [comment]
:+1:  - So we have two "providers" - Transitland and Transitfeeds. I'm using the Transitfeeds API from the Rpackage [gtfsr](https://github.com/ropenscilabs/gtfsr)
