### ISSUE TITLE
Geometrie che sembrano errate

### ISSUE THREAD

**Issue by aborruso** [openamat/Official-Data#7]
In corrispondenza degli shapes con ID `2430`, `4221` e `6030` ci sono delle strane rotte rettilinee che tagliano la città. Sembrano degli errori nei dati 

![image](https://cloud.githubusercontent.com/assets/30607/16894945/0ef58608-4b67-11e6-8560-c417552397d7.png)

**Comment by gbvitrano** [comment]
Anche questo è un errore, la polilinea taglia il territorio e non è chiusa.  Shapes_id 6030

![shapes_id_6030](https://cloud.githubusercontent.com/assets/20488693/16899336/b94c3586-4c00-11e6-8df8-9848b4a29af2.jpg)

**Comment by gbvitrano** [comment]
Nell'aggiornamento #openamat "amat_feed_gtfs_v9" shapes_id 2430 continua ad essere sbagliata
![shape_2430](https://cloud.githubusercontent.com/assets/20488693/17050009/e19f87ba-4ff0-11e6-85d4-433d7bf375d3.jpg)

**Comment by aborruso** [comment]
Chiuso con versione 10 del dataset a5c7bb4
