### ISSUE TITLE
Missing routes in the GTFS set

### ISSUE THREAD

**Issue by patperu** [openamat/Official-Data#9]
Hi,
I matched the route numbers from the [AMAT Webform](http://www.amat.pa.it/Le_Linee/linee_orario.php) with the "feriale" routes in the GTFS dataset
These "feriale" routes are not included in the GTFS set
https://gist.github.com/patperu/5826510e88126d7eb1039fbc3827021f

Ciao Patrick

**Comment by aborruso** [comment]
I'm closing it. I have created a complete list in #10
